create table Posts(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(200) NOT NULL
);

create table Workers(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	Surname NVARCHAR(100) NOT NULL,
	Patronymic NVARCHAR(100) NULL,
	PhoneNumber NVARCHAR(15) NULL,
	Post_ID INT FOREIGN KEY REFERENCES Posts(ID)
);

create table Users(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	[Login] NVARCHAR(100) NOT NULL,
	[Password] NVARCHAR(100) NOT NULL,
	Worker_ID INT FOREIGN KEY REFERENCES Workers(ID)
);

create table StatusRequests(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(MAX) NULL
);

create table Requests(
	ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	Title NVARCHAR(200) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	DateCreated DATE NOT NULL DEFAULT GETDATE(),
	DateExecution DATE NULL,
	Status_ID INT FOREIGN KEY REFERENCES StatusRequests(ID),
	Responsible_ID INT FOREIGN KEY REFERENCES Workers(ID),
	Dispatcher_ID INT FOREIGN KEY REFERENCES Workers(ID)
);

